### ISSUE TITLE
picca_cf1d crashes in local server

### ISSUE THREAD

**Issue by alxogm** [igmhub/picca#1031]
I tried to run picca_cf1d on the public EDR deltas in a local server and crashed, the other correlations worked well, while the same command in Perlmutter worked well. This was the error message. 

```
"/work/Verano23/miniconda3/envs/picca/lib/python3.11/multiprocessing/pool.p
y", line 774, in get
    raise self._value
IndexError: index 376996 is out of bounds for axis 0 with size 376996

```
It seems is due to the parallelization, any tip on how it could be solved?

**Comment by iprafols** [comment]
Have you checked that the wavelength limits are correct? Also, can you give more details on how to reproduce the error?

**Comment by alxogm** [comment]
It seems indeed is due to the limits. The error appears when picca_cf is run with the default parameters, even in Perlmutter, with the following 

```
picca_cf1d.py --out cf1d.fits --in-dir /global/cfs/cdirs/desi/public/edr/vac/edr/lya/fuji/v0.3/Delta/
done, npix = 194

computing xi: 0.0%
computing xi: 4.93%
computing xi: 9.86%
computing xi: 14.79%
computing xi: 19.72%
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/global/homes/a/alxogm/.conda/envs/picca_py39/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/global/homes/a/alxogm/.conda/envs/picca_py39/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/global/homes/a/alxogm/desi/code/igmhub/picca/bin/picca_cf1d.py", line 29, in corr_func
    correlation_function_data = cf.compute_xi_1d(p)
  File "/global/homes/a/alxogm/desi/code/igmhub/picca/py/picca/cf.py", line 1221, in compute_xi_1d
    xi1d[bins] += delta_times_weight * delta_times_weight[:, None]
IndexError: index 376996 is out of bounds for axis 0 with size 376996
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/homes/a/alxogm/desi/code/igmhub/picca/bin/picca_cf1d.py", line 352, in <module>
    main(cmdargs)
  File "/global/homes/a/alxogm/desi/code/igmhub/picca/bin/picca_cf1d.py", line 241, in main
    correlation_function_data = pool.map(corr_func, healpixs)
  File "/global/homes/a/alxogm/.conda/envs/picca_py39/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/global/homes/a/alxogm/.conda/envs/picca_py39/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: index 376996 is out of bounds for axis 0 with size 376996`
````
but it runs fine if I change the upper limit: 

`picca_cf1d.py --out cf1d.fits --in-dir /global/cfs/cdirs/desi/public/edr/vac/edr/lya/fuji/v0.3/Delta/ --lambda-max 5772
`
So should we just change the default upper limit?

**Comment by Waelthus** [comment]
If you run on #1036 with `--nproc 1` you get those more meaningful traces.

**Comment by Waelthus** [comment]
@alxogm please check if #1036 fixes the issue for you, then we can close this.

**Comment by alxogm** [comment]
@Waelthus I've tested the  branch both in NERSC and my local machine and it solved the issue. So we can close issue. Thanks!
