### ISSUE TITLE
Problem with new raeding of desi mocks

### ISSUE THREAD

**Issue by Cyeche** [igmhub/picca#388]
With the new strategy for nside in the reading of desi mocks, the code breaks  (I'm using python2)

Found 776 qsos
Traceback (most recent call last):
  File "bin/do_deltas.py", line 192, in <module>
    best_obs=args.best_obs, single_exp=args.single_exp, pk1d=args.delta_format )
  File "/Users/yeche/Develop/Pk1D/picca/py/picca/io.py", line 168, in read_data
    data = read_from_desi(nside,in_dir,thid,ra,dec,zqso,plate,mjd,fid,order)
  File "/Users/yeche/Develop/Pk1D/picca/py/picca/io.py", line 499, in read_from_desi
    in_nside = int(in_dir.split('spectra-')[-1].replace('/',''))
ValueError: invalid literal for int() with base 10: '..Spectra_desi'

**Comment by Cyeche** [comment]
Actually that’s fine I have just forgotten to add spectra-64/ to the path.  Sorry for the false alarm.
