### ISSUE TITLE
llvm error in picca_xdmat

### ISSUE THREAD

**Issue by iprafols** [igmhub/picca#588]
Running picca_xdmat.py I found a weird LLVM-related error. 

Here is the call:
```
python /home/iperez/software/picca/bin/picca_xdmat.py --in-dir /data/forest/iperez/SBLAs/deltas_lya_lyb_masksb/ --drq /data/forest/iperez/SBLAs/dla_dr14qv4_superbase_sourcez.fits.gz --out /data/forest/iperez/SBLAs/xdmat_dla_lya_lyb_dr14_baseline_v6_masksb_wz_superbase_sourcez.fits.gz --fid-Om 0.31457 --nproc 8 --nside 32 --z-evol-del 2.9 --z-evol-obj 0 --rej 0.9 
```

and here is the error:
```
computing xi: 0.0%
computing xi: 0.0%
computing xi: 0.001%
computing xi: 0.001%
computing xi: 0.002%
computing xi: 0.002%
computing xi: 0.002%
computing xi: 0.003%Traceback (most recent call last):
  File "/home/iperez/software/picca/bin/picca_xdmat.py", line 161, in <module>
    dm = pool.map(calc_dmat,sorted(list(cpu_data.values())))
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
RuntimeError: Failed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: object mode backend)
LLVM IR parsing error
<string>:7888:12: error: use of undefined value '%B0.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif'
  br label %"B0.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif"
           ^

```

**Comment by londumas** [comment]
@iprafols, it is a known issue, solved by using previous version of numba amd llvm.
Both of these packages team are working on it.
Please use the version of the pakage as defined there:
```
scipy==0.19.1
numpy==1.13.1
iminuit==1.3.3
healpy==1.11.0
fitsio==0.9.11
numba==0.41.0
llvmlite==0.26.0
h5py==2.6.0
future==0.16.0
setuptools==27.2.0
```

**Comment by londumas** [comment]
The version of the pakage are there: `https://github.com/igmhub/picca/blob/master/requirements.txt`
