### ISSUE TITLE
latest version of setuptools (40.8.0) does not build

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#591]
Latest version of setuptools (40.8.0) does not build, and fails the Travis tests.
It gives the following error:
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/picca_deltas.py", line 4, in <module>
    __import__('pkg_resources').run_script('picca==4.0', 'picca_deltas.py')
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1437, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/picca_deltas.py' not found in metadata at '/home/travis/build/igmhub/picca/py/picca.egg-info'
```
and
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/picca_deltas.py", line 4, in <module>
    __import__('pkg_resources').run_script('picca==4.0', 'picca_deltas.py')
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1437, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/picca_deltas.py' not found in metadata at '/home/travis/build/igmhub/picca/py/picca.egg-info'

```

**Comment by londumas** [comment]
Working on it in branch https://github.com/igmhub/picca/tree/use_latest_setuptools

**Comment by londumas** [comment]
"De guerre lasse", I asked for some help there: https://stackoverflow.com/questions/55733130/python-setup-py-install-does-not-work-with-latest-setuptools-no-scripts-in

**Comment by londumas** [comment]
Fixed in PR https://github.com/igmhub/picca/pull/698.
This was a very tough one to fix, the clue was in the following depreciation warning.
```
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
```

The solution was to replace `python setup.py test` with `pytest py/picca/test/test_cor.py -s`.
