### ISSUE TITLE
dmrp not defined in picca_export_coadd_zint.py

### ISSUE THREAD

**Issue by TEtourneau** [igmhub/picca#618]
```
picca_export_coadd_zint.py --data cf_z_0_2.2.fits cf_z_2.2_2.4.fits cf_z_2.4_2.6.fits cf_z_2.6_2.8.fits cf_z_2.8_3.0.fits cf_z_3.0_3.2.fits cf_z_3.2_10.fits --out cf_z_0_10-exp.fits

coadding healpix 1799 in file cf_z_3.2_10.fitsComputing cov...
smoothing 2499

Traceback (most recent call last):
  File "/global/homes/t/tetourne/.conda/envs/py27/bin/picca_export_coadd_zint.py", line 4, in <module>
    __import__('pkg_resources').run_script('picca==4.0', 'picca_export_coadd_zint.py')
  File "/global/homes/t/tetourne/.conda/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/global/homes/t/tetourne/.conda/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/global/homes/t/tetourne/.conda/envs/py27/lib/python2.7/site-packages/picca-4.0-py2.7.egg/EGG-INFO/scripts/picca_export_coadd_zint.py", line 112, in <module>
    
NameError: name 'dmrp' is not defined
```
I tried to coadd all the auto-correlation functions in:
`/global/cscratch1/sd/tetourne/Out/debug_2560_2/picca-0.1`

The distortion matrices are also present in the directory. They have the right name, but the fits files only have one hdu.
It looks like the line 112:
`elif dmrp.size==rp.size:`
should not try to access the dmrp variable.

**Comment by londumas** [comment]
Can you try the stack function in tutorials instead, and tell me if it
works ?

**Comment by londumas** [comment]
@TEtourneau, what version of picca did you use? Are you up-to-date with master?
As you can see there: https://github.com/igmhub/picca/blob/849e55d0e633d622ab79861e83795327a8254c56/bin/picca_dmat.py#L220,
you should have two HDUs. 
```
hdumasde@cori07:~> desi_header /global/cscratch1/sd/tetourne/Out/debug_2560_2/picca-0.1/dmat_z_0_2.2.fits --info
no key, will dump header
/global/cscratch1/sd/tetourne/Out/debug_2560_2/picca-0.1/dmat_z_0_2.2.fits
======================
Filename: /global/cscratch1/sd/tetourne/Out/debug_2560_2/picca-0.1/dmat_z_0_2.2.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       6   ()      
  1  DMAT          1 BinTableHDU     23   2500R x 2C   [D, 2500D]   

<bound method Header.tostring of SIMPLE  =                    T / file does conform to FITS standard             
BITPIX  =                   16 / number of bits per data pixel                  
NAXIS   =                    0 / number of data axes                            
EXTEND  =                    T / FITS dataset may contain extensions            
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H >
```

**Comment by TEtourneau** [comment]
Indeed the stack function in tutorials works !

I'm using the master of picca. But my files were computed sometime ago (something like 3 months).
So I guess it's just a problem of retro-compatibility.

**Comment by londumas** [comment]
indeed `tutorials/picca_export_stacked_correlation.py` is the function I use, because it is way faster. Non the less, `picca_export_coadd_zint.py` was suposed to be retro-compatbile. I will have a look.

**Comment by londumas** [comment]
fixed in PR https://github.com/igmhub/picca/pull/620
