### ISSUE TITLE
picca fails with latest numba

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#634]
While running the tests with the latest numba, `numba=0.44.0`, I get the following errors and warnings:

```
done, npix = 14
computing xi: 0.11%<HOME>Programs/igmhub/picca/py/picca/cf.py:103: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "fast_cf" failed type inference due to: non-precise type pyobject
[1] During: typing of argument at <HOME>Programs/igmhub/picca/py/picca/cf.py (105)

File "../cf.py", line 105:
def fast_cf(z1,r1,rdm1,w1,d1, z2,r2,rdm2,w2,d2, ang,same_half_plate):
    wd1 = d1*w1
    ^

  @jit
<HOME>.local/lib/python3.6/site-packages/numba/compiler.py:725: NumbaWarning: Function "fast_cf" was compiled in object mode without forceobj=True.

File "../cf.py", line 104:
@jit
def fast_cf(z1,r1,rdm1,w1,d1, z2,r2,rdm2,w2,d2, ang,same_half_plate):
^

  self.func_ir.loc))
<HOME>.local/lib/python3.6/site-packages/numba/compiler.py:734: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "../cf.py", line 104:
@jit
def fast_cf(z1,r1,rdm1,w1,d1, z2,r2,rdm2,w2,d2, ang,same_half_plate):
^

  warnings.warn(errors.NumbaDeprecationWarning(msg, self.func_ir.loc))
computing xi: 99.89%



read 0 of 5 0
read 1 of 5 1
read 2 of 5 283
read 3 of 5 526
read 4 of 5 680



done, npix = 14
computing xi: 0.11%<HOME>Programs/igmhub/picca/py/picca/cf.py:103: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "fast_cf" failed type inference due to: non-precise type pyobject
[1] During: typing of argument at <HOME>Programs/igmhub/picca/py/picca/cf.py (105)

File "../cf.py", line 105:
def fast_cf(z1,r1,rdm1,w1,d1, z2,r2,rdm2,w2,d2, ang,same_half_plate):
    wd1 = d1*w1
    ^

  @jit
<HOME>.local/lib/python3.6/site-packages/numba/compiler.py:725: NumbaWarning: Function "fast_cf" was compiled in object mode without forceobj=True.

File "../cf.py", line 104:
@jit
def fast_cf(z1,r1,rdm1,w1,d1, z2,r2,rdm2,w2,d2, ang,same_half_plate):
^

  self.func_ir.loc))
<HOME>.local/lib/python3.6/site-packages/numba/compiler.py:734: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "../cf.py", line 104:
@jit
def fast_cf(z1,r1,rdm1,w1,d1, z2,r2,rdm2,w2,d2, ang,same_half_plate):
^

  warnings.warn(errors.NumbaDeprecationWarning(msg, self.func_ir.loc))
computing xi: 99.89%



nproc 1
read 0 of 5 0
read 1 of 5 1
read 2 of 5 283
read 3 of 5 526
read 4 of 5 680



done, npix = 14
computing xi: 0.321%<HOME>Programs/igmhub/picca/py/picca/cf.py:186: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "fill_dmat" failed type inference due to: non-precise type pyobject
[1] During: typing of argument at <HOME>Programs/igmhub/picca/py/picca/cf.py (189)

File "../cf.py", line 189:
def fill_dmat(l1,l2,r1,r2,rdm1,rdm2,z1,z2,w1,w2,ang,wdm,dm,rpeff,rteff,zeff,weff,same_half_plate,order1,order2):
    <source elided>

    rp = (r1[:,None]-r2)*sp.cos(ang/2)
    ^

  @jit
<HOME>Programs/igmhub/picca/py/picca/cf.py:186: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "fill_dmat" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>

File "../cf.py", line 273:
def fill_dmat(l1,l2,r1,r2,rdm1,rdm2,z1,z2,w1,w2,ang,wdm,dm,rpeff,rteff,zeff,weff,same_half_plate,order1,order2):
    <source elided>
    ubb = sp.unique(m_bins)
    for k, (ba,m_ba) in enumerate(zip(bins,m_bins)):
    ^

  @jit
Traceback (most recent call last):
  File "<HOME>Programs/igmhub/picca/bin/picca_dmat.py", line 178, in <module>
    dm = list(dm)
  File "<HOME>Programs/igmhub/picca/bin/picca_dmat.py", line 17, in calc_dmat
    tmp = cf.dmat(p)
  File "<HOME>Programs/igmhub/picca/py/picca/cf.py", line 182, in dmat
    fill_dmat(l1,l2,r1,r2,rdm1,rdm2,z1,z2,w1,w2,ang,wdm,dm,rpeff,rteff,zeff,weff,same_half_plate,order1,order2)
  File "<HOME>.local/lib/python3.6/site-packages/numba/dispatcher.py", line 370, in _compile_for_args
    raise e
  File "<HOME>.local/lib/python3.6/site-packages/numba/dispatcher.py", line 327, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "<HOME>.local/lib/python3.6/site-packages/numba/dispatcher.py", line 659, in compile
    cres = self._compiler.compile(args, return_type)
  File "<HOME>.local/lib/python3.6/site-packages/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 955, in compile_extra
    return pipeline.compile_extra(func)
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 377, in compile_extra
    return self._compile_bytecode()
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 886, in _compile_bytecode
    return self._compile_core()
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 254, in run
    raise patched_exception
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 245, in run
    stage()
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 463, in stage_objectmode_frontend
    cres = self.frontend_looplift()
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 435, in frontend_looplift
    lifted=tuple(loops), lifted_from=None)
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 1017, in compile_ir
    lifted_from=lifted_from)
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 385, in compile_ir
    return self._compile_ir()
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 893, in _compile_ir
    return self._compile_core()
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 254, in run
    raise patched_exception
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 245, in run
    stage()
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 711, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 687, in _backend
    lowered = lowerfn()
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 659, in backend_object_mode
    self.flags)
  File "<HOME>.local/lib/python3.6/site-packages/numba/compiler.py", line 1148, in py_lowering_stage
    lower.lower()
  File "<HOME>.local/lib/python3.6/site-packages/numba/lowering.py", line 202, in lower
    self.library.add_ir_module(self.module)
  File "<HOME>.local/lib/python3.6/site-packages/numba/targets/codegen.py", line 185, in add_ir_module
    ll_module = ll.parse_assembly(ir)
  File "<HOME>.local/lib/python3.6/site-packages/llvmlite/binding/module.py", line 26, in parse_assembly
    raise RuntimeError("LLVM IR parsing error\n{0}".format(errmsg))
RuntimeError: Failed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: object mode backend)
LLVM IR parsing error
<string>:2454:50: error: expected type
  %".1157" = call i8* @"PyLong_FromSsize_t"(i64 (slice(None, None, None), None))
                                                 ^



F
======================================================================
FAIL: test_cor (__main__.TestCor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cor.py", line 69, in test_cor
    self.send_dmat()
  File "test_cor.py", line 521, in send_dmat
    self.compare_fits(path1,path2,"picca_dmat.py")
  File "test_cor.py", line 219, in compare_fits
    self.assertTrue(os.path.isfile(path2),"{}".format(nameRun))
AssertionError: False is not true : picca_dmat.py

----------------------------------------------------------------------
Ran 1 test in 94.397s

FAILED (failures=1)

```

**Comment by andreufont** [comment]
This is still an issue when I run Picca at NERSC (my screen gets polluted by tones of warnings)

**Comment by julianbautista** [comment]
I will close this since everything is working and the warning messages are reported in #684
