### ISSUE TITLE
computing all minos errors fails

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#645]
Computing minos errors on all parameters give the following error, however none are raised when computing using the name of the parameters.
It comes from the fact that using `all`, iminuit gives a `numpy.str_` and using the name of the parameters we get `str`.

```
[minos]
sigma = 1.0
parameters = all
```

```
Traceback (most recent call last):
  File "/uufs/astro.utah.edu/common//u6011908/Programs/igmhub/picca/bin/picca_fitter2.py", line 23, in <module>
    chi.export()
  File "/uufs/astro.utah.edu/common//u6011908/Programs/igmhub/picca/py/picca/fitter2/chi2.py", line 374, in export
    subgrp.attrs[item] = value
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/uufs/astro.utah.edu/common//u6011908/.local/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 95, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/uufs/astro.utah.edu/common//u6011908/.local/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 177, in create
    htype = h5t.py_create(original_dtype, logical=True)
  File "h5py/h5t.pyx", line 1630, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1652, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1713, in h5py.h5t.py_create
TypeError: No conversion path for dtype: dtype('<U2')
```

```
name ap <class 'str'> <class 'numpy.str_'>
```

```
name ap <class 'str'> <class 'str'>
```

**Comment by londumas** [comment]
fixed in https://github.com/igmhub/picca/pull/646
