### ISSUE TITLE
effective-bins bugs when using combined fit

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#647]
@vserret, I am trying to have your `effective-bins` computation working when using a combined fit, and it does not. The following command line works for a single correlation, but not for a combined. Have you ever tried it on combined results? Could you fix the code? I get the following error, that tells me that line 157 is trying to read all the config files at once.
```
$HOME/Programs/igmhub/picca/py/picca/fitter2/effective-bins.py
--chi2-file chi2.ini
--cor-name cf_z_0_10
--params ap at
--plot-effective-bins
```

```
INFO: reading input Pk <HOME>/Programs/igmhub/picca/py/picca/fitter2/models/PlanckDR16/PlanckDR16.fits
INFO: reading <Data>/Correlations/Fit/allCombined_z_0_10_noMet/config_cf.ini
LOG: Full matrix is positive definite
LOG: Reduced matrix is positive definite
INFO: reading <Data>/Correlations/Fit/allCombined_z_0_10_noMet/config_xcf.ini
LOG: Full matrix is positive definite
LOG: Reduced matrix is positive definite
INFO: reading <Data>/Correlations/Fit/allCombined_z_0_10_noMet/config_cf_LYA_in_LYA_LYA_in_LYB.ini
LOG: Full matrix is positive definite
LOG: Reduced matrix is positive definite
INFO: reading <Data>/Correlations/Fit/allCombined_z_0_10_noMet/config_xcf_LYA_in_LYB_z_0_10.ini
LOG: Full matrix is positive definite
LOG: Reduced matrix is positive definite
HELO
INFO: reading <Data>/Correlations/Fit/allCombined_z_0_10_noMet/config_cf.ini <Data>/Correlations/Fit/allCombined_z_0_10_noMet/config_xcf.ini <Data>/Correlations/Fit/allCombined_z_0_10_noMet/config_cf_LYA_in_LYA_LYA_in_LYB.ini <Data>/Correlations/Fit/allCombined_z_0_10_noMet/config_xcf_LYA_in_LYB_z_0_10.ini
Traceback (most recent call last):
  File "computer/3.6.3/lib/python3.6/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<HOME>/Programs/igmhub/picca/py/picca/fitter2/effective-bins.py", line 158, in <module>
    ico,rp,rt,np,nt,rp_min,rp_max,rt_min,rt_max,r_min,r_max,z = extract_data(chi2_file,dic_init)
  File "<HOME>/Programs/igmhub/picca/py/picca/fitter2/effective-bins.py", line 47, in extract_data
    cp.get('data sets','zeff'),dic_init['fiducial'])
  File "<HOME>/Programs/igmhub/picca/py/picca/fitter2/parser.py", line 105, in parse_data
    for item, value in cp.items('data'):
  File "<computer>/3.6.3/lib/python3.6/configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'data'
```

**Comment by vserret** [comment]
I have made it for singe fits. When I want combined fit I just add the values for w*z and w.

**Comment by londumas** [comment]
Fixed in https://github.com/igmhub/picca/pull/653
