### ISSUE TITLE
h5py error when exporting fitter2 results

### ISSUE THREAD

**Issue by julianbautista** [igmhub/picca#709]
I was following the [DESI HackDR14 tutorial ](https://desi.lbl.gov/trac/wiki/LymanAlphaWG/ReproduceSDSS/HackDR14) at NERSC. 

The continuum fitting and correlation function were successful. 
However when fitting the cross-correlation with
`picca_fitter2.py Fits/xcf_lya_kaiser/chi2.ini`

I obtain the following error message:

```Traceback (most recent call last):
  File "/global/homes/j/jbautist/software/picca/bin/picca_fitter2.py", line 23, in <module>
    chi.export()
  File "/global/homes/j/jbautist/.local/cori/3.7-anaconda-2019.10/lib/python3.7/site-packages/picca-4.0-py3.7.egg/picca/f
itter2/chi2.py", line 293, in export
  File "/global/homes/j/jbautist/.local/cori/3.7-anaconda-2019.10/lib/python3.7/site-packages/h5py/_hl/files.py", line 40
8, in __init__
    swmr=swmr)
  File "/global/homes/j/jbautist/.local/cori/3.7-anaconda-2019.10/lib/python3.7/site-packages/h5py/_hl/files.py", line 17
9, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to lock file, errno = 524, error message = 'Unknown error 524')
```

Ideas? I have version 2.10 of h5py

**Comment by andreicuceu** [comment]
Hi @julianbautista, this error usually appears when you don't have write permissions for either the output folder (and it's trying to create a new file in it) or the output file which already exists. I've also seen this before at NERSC when trying to run with MPI and h5py doesn't like it for some reason, but I haven't figured out why yet.

**Comment by andreufont** [comment]
Hi @julianbautista - is this still not working? If not, it might be worth asking NERSC support, they are usually good at this.
