### ISSUE TITLE
Keyword name problem in continuum fitting (picca_deltas.py)

### ISSUE THREAD

**Issue by Andrea-MG** [igmhub/picca#750]
I am trying to run picca_deltas.py on a mock with this instruction:

`picca_deltas.py --drq Catalog/zcat_desi_drq.fits --in-dir /global/cfs/projectdirs/desi/mocks/lya_forest/develop/london/qq_desi/v9.0_Y1/monthly_delay0_v0/desiY1-0.2-metals/spectra-16/ --out-dir Delta_LYA/Delta/ --mode desi --iter-out-prefix Delta_LYA/Log/delta_attributes --log Delta_LYA/Log/input.log`

And after reading the data I get the error:

`Continuum fitting: starting iteration 0 of 5
Continuum fitting: ending iteration 0 of 5
 Mean quantities in observer-frame
 loglam    eta      var_lss  fudge    chi2     num_pix 
Traceback (most recent call last):
  File "/global/homes/a/andreamg/Programs/Picca_2020/picca/bin/picca_deltas.py", line 942, in <module>
    main()
  File "/global/homes/a/andreamg/Programs/Picca_2020/picca/bin/picca_deltas.py", line 652, in main
    (args.vlss_min, args.vlss_max))
  File "/global/homes/a/andreamg/Programs/Picca_2020/picca/py/picca/prep_del.py", line 243, in compute_var_stats
    limit_fudge=(0, None))
  File "iminuit/_libiminuit.pyx", line 555, in iminuit._libiminuit.Minuit.__init__
  File "iminuit/_libiminuit.pyx", line 90, in iminuit._libiminuit.check_extra_args
RuntimeError: Cannot understand keyword name. May be a typo?
The parameters are ['eta', 'var_lss', 'fudge']
`

Any ideas on how to solve this are appreciated! :)

**Comment by iprafols** [comment]
Hi @Andrea-MG, 
What version of python are you using?  And of iminuit?
This error seems familiar to me and if I recall it correctly it was related to not having the correct versions of the libraries
Cheers,
I.

**Comment by iprafols** [comment]
I believe the problem is that in the DESI environment in NERSC, the iminuit version is 1.4.2. This issue is solved using version 1.5.2.

**Comment by iprafols** [comment]
This is outdated as both DESI environment and PICCA has moved to iminuit 2.x.
